### ISSUE TITLE
数据库-MySQL SQL 优化 答案不准确

### ISSUE THREAD

**Issue by helloworlde** [xbox1994/Java-Interview#12]
> 问：有个表特别大，字段是姓名、年龄、班级，如果调用select * from table where name = xxx and age = xxx该如何通过建立索引的方式优化查询速度？
答：由于mysql查询每次只能使用一个索引，如果在name、age两列上创建复合索引的话将带来更高的效率。如果我们创建了(name, age)的复合索引，那么其实相当于创建了(name, age)、(name)三个索引，这被称为最佳左前缀特性。因此我们在创建复合索引时应该将最常用作限制条件的列放在最左边，依次递减。其次还要考虑该列的数据离散程度，如果有很多不同的值的话建议放在左边，name的离散程度也大于age。

这里的 (name,age) 索引使用的不是最左前缀原则，而是索引下推
最左前缀原则用于 `name like 'A%'`这样的查询，会使用到索引，加速查询
索引下推是指在索引遍历的过程中优先对索引中包含的字段做判断，不满足条件的直接过滤，减少回表次数

**Comment by xbox1994** [comment]
谢谢，该原则我没有解释清楚，会立即更正。

最左前缀匹配原则：在mysql建立联合索引时会遵循最左前缀匹配的原则，即最左优先，在检索数据时从联合索引的最左边开始匹配。mysql会一直向右匹配直到遇到范围查询（>/</between/like）就停止匹配，比如a=3 and b=4 and c>5 and d=6，如果建立（a,b,c,d）联合索引，d就用不到索引，如果建立（a,b,d,c）则都能用到索引。

>这里的 (name,age) 索引使用的不是最左前缀原则，而是索引下推

对于这条sql语句，使用到了最左前缀匹配原则，从name开始匹配，匹配到了name和age，才能使用到联合索引。我做过实验，改sql并没有使用索引下推。
[索引下推的条件](https://dev.mysql.com/doc/refman/5.6/en/index-condition-pushdown-optimization.html)是使用Innodb的二级索引有并试图访问全表行的操作如范围查询。

>最左前缀原则用于 name like 'A%'这样的查询，会使用到索引，加速查询

最左前缀原则不只用于like查询，具体规则在上面提到
