### ISSUE TITLE
算法题目和解法没对应上吧？

### ISSUE THREAD

**Issue by GalaxyGuan12** [xbox1994/Java-Interview#15]
https://github.com/xbox1994/2018-Java-Interview/blob/master/MD/%E7%AE%97%E6%B3%95-%E6%95%B0%E7%BB%84-%E5%BF%AB%E9%80%9F%E6%8E%92%E5%BA%8F-%E7%AC%ACk%E5%A4%A7%E4%B8%AA%E6%95%B0.md
这一题

**Comment by xbox1994** [comment]
谢谢，已更正
