### ISSUE TITLE
在java 基础多线程篇中的最后一个奇偶打印的编程题

### ISSUE THREAD

**Issue by spland** [xbox1994/Java-Interview#16]
我不太理解为什么要加上t1.join();t2.join();这两行代码，我不加结果是一样的呀，加了的话意义在哪里呢？

**Comment by xbox1994** [comment]
你可以在最后一行代码后面加上`System.exit(0);`让JVM执行完成之后立即退出就清楚了

**Comment by spland** [comment]
> 你可以在最后一行代码后面加上`System.exit(0);`让JVM执行完成之后立即退出就清楚了

噢，懂了，感谢
