### ISSUE TITLE
反转二叉树写的有问题吧

### ISSUE THREAD

**Issue by jarvisqi** [xbox1994/Java-Interview#3]
如题，反转打印那里写的不对

    TreeNode currentLineRightestNode = this;
    .....
    
    if (currentNode.value == currentLineRightestNode.value) {
                    System.out.println();
                    currentLineRightestNode.value = nextLineRightestNode.value;
                }
    currentLineRightestNode.value = nextLineRightestNode.value;

这样赋值之后，TreeNode 不就被修改了吗？

**Comment by xbox1994** [comment]
是个BUG，已经在[这个提交](https://github.com/xbox1994/2018-Java-Interview/commit/baa96f9969edc7cde5012e420459c75a06c78b21)修复，非常感谢
