### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by cloader** [xbox1994/Java-Interview#6]
ThreadLocal
使用ThreadLocal<UserInfo> userInfo = new ThreadLocal<UserInfo>()的方式，让每个线程内部都会维护一个ThreadLocalMap，里边包含若干了 Entry（K-V 键值对），每次存取都会先**的都**当前线程，然后得到该线程对象中的Map，然后与Map交互。

此处有错别字

**Comment by xbox1994** [comment]
谢谢，已更正

**Comment by cloader** [comment]
优化SQL语句和索引，在where/group by/order by中用到的字段建立索引，索引字段越小越好，复合索引**简历**的顺序

此处有错别字

**Comment by cloader** [comment]
主要使用B+树来构建索引，为什么不用二叉树是因为B+树是多叉的，可以减少树的高度，还有**事**索引本身较大

此处有错别字

**Comment by xbox1994** [comment]
已更正

**Comment by yanglbme** [comment]
@cloader 
可以直接提交 pr 帮 @xbox1994 fix typo 😄
