### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by yanglbme** [xbox1994/Java-Interview#7]
😄 这是一个很不错的 repo。

- 关于高并发、分布式、高可用这一块的相关面试题及相关剖析，可以参考[这里](https://github.com/doocs/advanced-java)。
- 文档的书写还是要规范一些，比如中文与数字之间用空格隔开。

**Comment by xbox1994** [comment]
谢谢你的建议，很有参考价值，我会继续优化。

你总结的repo在分布式架构方面比较全面，如果可以的话希望能引用你的总结，当然我会给出来源。

**Comment by yanglbme** [comment]
@xbox1994 
Of course, 欢迎引用~
